### ISSUE TITLE
Readme.md 수정 필요합니다.

### ISSUE THREAD

**Issue by ghost** [19-2-SKKU-OSS/2019-2-OSS-L9#1]
- 자세한 팀원 소개
- 프로젝트 설명

등의 항목이 개선되었으면 좋겠습니다.

**Comment by ahnhyunjun417** [comment]
각자 팀원 소개는 자기 스스로 Readme 고치는 걸로 할까요?

**Comment by ghost** [comment]
어느정도 통일된 양식으로 고치는게 좋을거 같은데 각자 고치면 너무 제각각일거 같아서 저는 한명이 했으면 좋겠습니다.

**Comment by lcw921** [comment]
팀원 소개, 프로젝트 설명 모두 한 명이 하기에는 양이 적지 않습니다. 정 한 명이 하게 하고 싶다면, 
소개 양식을 정해서 그 부분에 따른 내용을 각자 작성한 뒤에 한 명이 정리해서 올리는 수준이 좋을 것 같습니다.

**Comment by lcw921** [comment]
프로젝트 설명은 무슨 내용이 들어가야할지 상의를 해보고 그 다음에 정하는 걸로 하는게 어떨까요?
내용이 많으면 한 명이 하긴 어려울거고, 내용이 적다면 한 명이 할 수 있을테니까요.

**Comment by ghost** [comment]
그러면 이번 화요일 날 모였을때 자기소개 양식 및 나머지 프로젝트 설명 등을 어떻게 작성할지 논의해보는건 어떨까요?

**Comment by lcw921** [comment]
좋습니다.
