### ISSUE TITLE
수정할 부분 탐색

### ISSUE THREAD

**Issue by ghost** [19-2-SKKU-OSS/2019-2-OSS-L9#2]
각자 이 프로젝트에 대해서 기여할 부분을 찾아야 할 것 같습니다. 이번 이슈에서 해결했으면 좋겠네요.

**Comment by ahnhyunjun417** [comment]
지금 돌아보고 왔구요. 저는 LinkedList의 곱셈 쪽을 해볼까 생각중입니다. linked list로 곱셈하고 그리고 테스트 케이스도 몇개 추가하려고 합니다.

**Comment by ahnhyunjun417** [comment]
우선 우리가 clone 한 저장소 링크라도 달게요

**Comment by ahnhyunjun417** [comment]
우리 그리고 그 자기소개 부분을 
이름
학번 
소속
역할 및 업무
식으로 정리하는게 좋을 거 같은데 어떻게 생각하시나요?

**Comment by lcw921** [comment]
> 우리 그리고 그 자기소개 부분을
> 이름
> 학번
> 소속
> 역할 및 업무
> 식으로 정리하는게 좋을 거 같은데 어떻게 생각하시나요?

좋은 것 같습니다. 간단한 자기소개(관심분야나 기존 프로젝트?) 정도 추가하면 좋을 것 같아요.
그 내용을 각자 다들 적어서 모은 다음 정리하는게 좋을 것 같습니다.

**Comment by lcw921** [comment]
저는 graph 전반에 대한 문제들에 관여하고 싶습니다.
원래 저장소에 새로운 이슈로 
Add Maximum Flow Ford Fulkerson Algorithm #595 라는 이슈가 올라왔는데, 이런 이슈를 해결하는 것도 가능한 수준으로 보여서 관리자가 괜찮다고 한다면 해볼까 합니다.
그 외에도 기존에 풀었던 문제에서 시간 복잡도를 여러 방면으로 분석한 내용들을 추가할까 합니다.
주로 그래프에 대한 내용을 다루고 싶습니다.

**Comment by ghost** [comment]
> 우리 그리고 그 자기소개 부분을
> 이름
> 학번
> 소속
> 역할 및 업무
> 식으로 정리하는게 좋을 거 같은데 어떻게 생각하시나요?

이 부분은 #1 에서 얘기해주시면 감사하겠습니다
